### ISSUE TITLE
user-can-search-for-a-tv-show

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/TV-shows-to-Binge#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user is able to search for a TV show

## 📐 Functionality
> ##### A description of how the application will work from the perspective of the user.

Create a responsive page that allows the user to type in a title of a TV show 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1113" alt="Screenshot 2022-11-14 at 3 22 57 PM" src="https://user-images.githubusercontent.com/113474457/201788595-3b34719d-cab4-444d-87e0-b1febc31de80.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add the 'binge' logo and a 'home' icon to the `header` in HTML
- [x] Add the search bar with a magnifying glass icon within the `main` element
- [x] Ensure that the page looks nice on both mobile-sized AND desktop-sized screens
- [x] Generate an XMLHttpRequest object and send a request using the title name to grab its TV ID [http https://api.watchmode.com/v1/search/?apiKey=YOUR_API_KEY search_field=='name' search_value=='string']
- [x] Ensure the TV ID will be returned from the API data 
- [x] Once the previous step is completed, generate a new XMLHttpRequest object and send another request using the TV ID that was returned to grab the details of the specific TV show. [https://api.watchmode.com/v1/title/TVID/details/apiKey=YOUR_API_KEY&append_to_response=sources]
- [x] Ensure that the `IMG`, `year`, `tv rating`, `title`, `seasons`, `genre`, and `us_rating` information is returned. 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented-out codes.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
