### ISSUE TITLE
user-can-search-to-see-preview

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/TV-shows-to-Binge#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for a TV show by title to see the summary page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can search for a TV show by title to view the summary page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1015" alt="Screenshot 2022-11-16 at 1 48 22 PM" src="https://user-images.githubusercontent.com/113474457/202301735-a4e927ce-73c2-4c0b-8ebb-c8ab732ba8cf.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling `div[data-view="summary-page"]` to the HTML
- [x] Add a dummy TV Show Summary Page layout to the `div` element in the HTML and style them to match the wireframe
- [x] Create a view-swapping function to display the TV Show summary page while hiding the search bar and return a DOM tree that matches the wireframe example.
- [x] Check that the dummy summary page looks good on both mobile AND desktop screens
- [x] Listen for `'click'` events on the 'home' icon to go back to the home page in order to search for another TV show while removing the previous search history
- [x] Listen for `'click'` event on the 'magnifying glass' icon to have an alternate way to search for a TV show which should allow view-swapping function to display the TV show summary page while hiding the search bar.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
