### ISSUE TITLE
user-can-add-a-show-to-my-list

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/TV-shows-to-Binge#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can add a show to the 'My-List' page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users are able to click on the '+' button to add the show to the 'My-list' page which will turn the '+' into a 'check mark' to indicate that the TV show has been added to 'My-List'
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-11-14 at 3 39 05 PM](https://user-images.githubusercontent.com/113474457/201790545-0c1e5cb5-3df0-4c3a-ab6c-1fffbe722f35.png)
<img width="1047" alt="Screenshot 2022-11-16 at 3 21 42 PM" src="https://user-images.githubusercontent.com/113474457/202315923-31a92fee-0329-4fe3-9d2e-ea724ef88f01.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add `button` to the TV show's summary card
- [x] Listen for the `submit` event on the 'plus' button icon to add the TV show to 'My-List' **AND**:
- [x] Put the form's input values into a new object (Poster Photo Only)
- [x] Set up local storage for the data model
- [x] Add the `nextEntryId` to the object
- [x] Increment the `nextEntryId` on the data  model
- [x] Append the new object to the entries in the data model
- [x] Add a 'list' icon to the header next to the 'home' icon
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
