### ISSUE TITLE
user-can-view-the-show-in-a-list

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/TV-shows-to-Binge#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
Users can view the show they added to a list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Once the user adds a show to 'My-List', the user is able to click on the 'list' icon in the header to go to the 'My-List' page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-11-17 at 10 52 03 PM](https://user-images.githubusercontent.com/113474457/202639670-9eef56c7-1e53-4cc9-b418-4b352fc505bc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Listen for a 'click' event on the 'List' icon to be able to go to the 'My-List' page
- [x] Add a sibling `div[data-view="my-list"]` to the HTML 
- [x] Add an empty unordered list to the `div[data-view="my-list"]` element in the HTML
- [x] Add a dummy saved TV show poster list to the unordered list in the HTML and style them to match the wireframe
- [x] Create a DOM tree to be rendered into the 'My-List' 
- [x] Use a loop to create a DOM tree for each TV Show card in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML layout once the TV Show poster card is successfully appended to the 'My-List' page. 
- [x] Listen for a `'click'` event on the unordered list element to view a summary of the TV show clicked again
- [x] Ensure that refreshing the pages shows the same view as before refreshing
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
