### ISSUE TITLE
User-can-remove-the-show-from-the-list

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/TV-shows-to-Binge#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can remove one or more shows from the 'My-List'
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users are able to remove a show from the list once they finished watching the TV show or when the user becomes uninterested.

The user is able to click on a poster to see the summary page again in order to delete a TV show from the 'My List' page. 
Upon deletion, it will take the user to 'My List' page where the changes will be reflected.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="826" alt="Screenshot 2022-11-18 at 4 14 09 PM" src="https://user-images.githubusercontent.com/113474457/202823426-2c52d6d9-3e11-4077-a8dd-34ac584017f7.png">
eenshot 2022-11-18 at 4.14.18 PM.png…]

<img width="1107" alt="Screenshot 2022-11-18 at 4 14 18 PM" src="https://user-images.githubusercontent.com/113474457/202823461-8686a69d-5815-4b1a-b774-284617653051.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Have the 'trash can' icon only appear when the user clicks on the poster in my 'My-List'
- [x] Add a click target for deleting a TV show card from 'My-List' 
- [x] Show a confirmation modal when the user clicks the 'trash can' icon 
- [x] Hide the modal if the user clicks Cancel
- [x] Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Delete.
- [x] Show the updated 'My List' list if the user clicks Delete
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
